parameters:
#    register_user.example.class: Register\UserBundle\Example

services:
    register_user.registration.form.type:
        class: Register\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: register_user_registration }

    register_user.profile.form.type:
        class: Register\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: register_user_profile }
#    register_user.example:
#        class: %register_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
